In [1]:
import numpy as np
import sys

FreeCodeCamp

Initializing 1D and 2D numpy array

In [2]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# here it could be np.int8,np.int16,np.int32,np.int64
# here np.int8 --> means 8 bit integer
# here np.int16 --> means 16 bit integer
# here np.int32 --> means 32 bit integer
# here np.int64 --> means 64 bit integer
c=np.array([5,6,7,8,9],np.int64)
print(c)

[5 6 7 8 9]


Some Basic Operations

In [5]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get Size
print(a.size)
print(b.size)

3
6


In [8]:
# Get dtype
print(a.dtype)
print(b.dtype)

int16
float64


In [9]:
# Get Size
print(a.itemsize)
print(b.itemsize)

2
8


In [10]:
# Get Total Size
# nbytes = size * itemsize
print('Total Size of a =',a.size*a.itemsize)
print('Total Size of a =',a.nbytes)
print('Total Size of b =',b.size*b.itemsize)
print('Total Size of b =',b.nbytes)

Total Size of a = 6
Total Size of a = 6
Total Size of b = 48
Total Size of b = 48


Accessing/Changing specific elements, rows, columns etc

In [11]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r,c]
print(a[1,5])
print(a[1,-2])

13
13


In [13]:
# Get a specific row
print(a[0,:])
print(a[1,:])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [14]:
# Get a specific column
print(a[:,3])

[ 4 11]


In [15]:
# Getting a little more fancy [start_index:ending_index:step_size]
print(a[0,1:6:2])
print(a[0,1:-1:2])
print(a[0,-6:-1:2])


[2 4 6]
[2 4 6]
[2 4 6]


In [16]:
a[1,5]=20
print(a)
a[:,2]=5
print(a)
a[:,2]=[3,10]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


3 D Example

In [17]:
# layers,rows,columns
b = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get Specific element
print(b[0,1,1])
print(b[:,0,:])
print(b[0,0,:])
print(b[:,0,0])


4
[[1 2]
 [5 6]]
[1 2]
[1 5]


In [19]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initializing different types of array

In [20]:
# All 0s matrix
c=np.zeros(5)
print(c)
d=np.zeros((2,3))
print(d)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# All 1s matrix
e=np.ones((4,3,2),dtype='int32')
print(e)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [22]:
# Any other number
e=np.full((2,2),99)
print(e)

[[99 99]
 [99 99]]


In [23]:
# Any other number full_like
f=np.full_like(a,4)
print(f)

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [24]:
# Random Decimal Numbers
g=np.random.rand(4,2,2) # shape pass kari hai basically idhar
print(g)

[[[0.88450465 0.27260376]
  [0.49355433 0.31094377]]

 [[0.1852743  0.79747992]
  [0.96562397 0.53316306]]

 [[0.52374267 0.12849354]
  [0.0839712  0.26818782]]

 [[0.75541885 0.40393461]
  [0.63655074 0.8028789 ]]]


In [25]:
h=np.random.random_sample(a.shape)
print(h)

[[0.80648768 0.68010687 0.43215393 0.99056874 0.40678647 0.11847146
  0.0262145 ]
 [0.3557564  0.4917707  0.18677633 0.35504908 0.88912221 0.52669494
  0.48870103]]


In [26]:
# Random Integer Values
i=np.random.randint(-9,10,size=(3,3))
print(i)

[[ 6 -7  7]
 [ 9  0  5]
 [ 2  2 -8]]


In [27]:
# Identity Matrix
j=np.identity(3)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# Repeat an Array
arr=np.array([[1,2,3]])
c1=np.repeat(arr,3,axis=0)
print(c1)
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [29]:
arr2=np.ones((5,5))
print(arr2)
z=np.zeros((3,3))
z[1,1]=9
print(z)
arr2[1:4,1:-1]=z
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
# Linearly spaced elements 1 se 50 tak 12 elements
lspace=np.linspace(1,50,12)
print(lspace)

[ 1.          5.45454545  9.90909091 14.36363636 18.81818182 23.27272727
 27.72727273 32.18181818 36.63636364 41.09090909 45.54545455 50.        ]


In [31]:
arr=np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


Copying Arrays

In [32]:
# Here if we change b, a will be changed as well as both point to same thing
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [33]:
# We use .copy() method to copy array
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics

In [34]:
a=np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [35]:
b=np.array([1,0,1,0])
print(a+b)

[2 2 4 4]


In [36]:
# Taking sin,cos
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Linear Algebra

In [37]:
# Multiplying Matrices
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [38]:
# Can Do Many More Operations 
# Determinant
# Trace
# Singular Value Decomposition
# Eignevalues
# Matrix Norm
# Inverse
# etc

Statistics

In [39]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
[1 2 3]
[1 4 7]


In [41]:
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

9
[7 8 9]
[3 6 9]


In [42]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

45
[12 15 18]
[ 6 15 24]


Reorganizing Array

In [43]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
after=before.reshape((4,2))
print(after)
after=np.reshape(before,(2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# Vertically Stack
a=[1,2,3,4]
b=[5,6,7,8]
c=np.vstack([a,b,a,b])
print(c)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [45]:
# Horizontally Stack
a=[[1,2,3,4],[5,6,7,8]]
b=[[9,10,11,12],[13,14,15,16]]
c=np.hstack((a,b))
print(c)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


Miscellaneous

In [46]:
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)
filedata=filedata.astype(np.int32)
print(filedata)

ValueError: Some errors were detected !
    Line #3 (got 2 columns instead of 1)
    Line #8 (got 2 columns instead of 1)
    Line #13 (got 2 columns instead of 1)
    Line #18 (got 2 columns instead of 1)
    Line #23 (got 2 columns instead of 1)
    Line #28 (got 2 columns instead of 1)
    Line #33 (got 2 columns instead of 1)
    Line #38 (got 2 columns instead of 1)
    Line #43 (got 2 columns instead of 1)
    Line #48 (got 2 columns instead of 1)
    Line #53 (got 2 columns instead of 1)
    Line #58 (got 2 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #68 (got 2 columns instead of 1)
    Line #73 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #83 (got 2 columns instead of 1)
    Line #88 (got 2 columns instead of 1)
    Line #93 (got 2 columns instead of 1)
    Line #98 (got 2 columns instead of 1)
    Line #103 (got 2 columns instead of 1)
    Line #108 (got 2 columns instead of 1)
    Line #113 (got 2 columns instead of 1)
    Line #118 (got 2 columns instead of 1)
    Line #123 (got 2 columns instead of 1)
    Line #128 (got 2 columns instead of 1)
    Line #133 (got 2 columns instead of 1)
    Line #138 (got 2 columns instead of 1)
    Line #143 (got 2 columns instead of 1)
    Line #148 (got 2 columns instead of 1)
    Line #153 (got 2 columns instead of 1)
    Line #158 (got 2 columns instead of 1)
    Line #163 (got 2 columns instead of 1)
    Line #168 (got 2 columns instead of 1)
    Line #173 (got 2 columns instead of 1)
    Line #178 (got 2 columns instead of 1)
    Line #183 (got 2 columns instead of 1)
    Line #188 (got 2 columns instead of 1)
    Line #193 (got 2 columns instead of 1)
    Line #198 (got 2 columns instead of 1)
    Line #203 (got 2 columns instead of 1)
    Line #208 (got 2 columns instead of 1)
    Line #213 (got 2 columns instead of 1)
    Line #218 (got 2 columns instead of 1)
    Line #223 (got 2 columns instead of 1)
    Line #228 (got 2 columns instead of 1)
    Line #233 (got 2 columns instead of 1)
    Line #238 (got 2 columns instead of 1)
    Line #243 (got 2 columns instead of 1)
    Line #248 (got 2 columns instead of 1)
    Line #253 (got 2 columns instead of 1)
    Line #258 (got 2 columns instead of 1)
    Line #263 (got 2 columns instead of 1)
    Line #268 (got 2 columns instead of 1)
    Line #273 (got 2 columns instead of 1)
    Line #278 (got 2 columns instead of 1)
    Line #283 (got 2 columns instead of 1)
    Line #288 (got 2 columns instead of 1)
    Line #293 (got 2 columns instead of 1)
    Line #298 (got 2 columns instead of 1)
    Line #303 (got 2 columns instead of 1)
    Line #308 (got 2 columns instead of 1)
    Line #313 (got 2 columns instead of 1)
    Line #318 (got 2 columns instead of 1)
    Line #323 (got 2 columns instead of 1)
    Line #328 (got 2 columns instead of 1)
    Line #333 (got 2 columns instead of 1)
    Line #338 (got 2 columns instead of 1)
    Line #343 (got 2 columns instead of 1)
    Line #348 (got 2 columns instead of 1)
    Line #353 (got 2 columns instead of 1)
    Line #358 (got 2 columns instead of 1)
    Line #363 (got 2 columns instead of 1)
    Line #368 (got 2 columns instead of 1)
    Line #373 (got 2 columns instead of 1)
    Line #378 (got 2 columns instead of 1)
    Line #383 (got 2 columns instead of 1)
    Line #388 (got 2 columns instead of 1)
    Line #393 (got 2 columns instead of 1)
    Line #398 (got 2 columns instead of 1)
    Line #403 (got 2 columns instead of 1)
    Line #408 (got 2 columns instead of 1)
    Line #413 (got 2 columns instead of 1)
    Line #418 (got 2 columns instead of 1)
    Line #423 (got 2 columns instead of 1)
    Line #428 (got 2 columns instead of 1)
    Line #433 (got 2 columns instead of 1)
    Line #438 (got 2 columns instead of 1)
    Line #443 (got 2 columns instead of 1)
    Line #448 (got 2 columns instead of 1)
    Line #453 (got 2 columns instead of 1)
    Line #458 (got 2 columns instead of 1)
    Line #463 (got 2 columns instead of 1)
    Line #468 (got 2 columns instead of 1)
    Line #473 (got 2 columns instead of 1)
    Line #478 (got 2 columns instead of 1)
    Line #483 (got 2 columns instead of 1)
    Line #488 (got 2 columns instead of 1)
    Line #493 (got 2 columns instead of 1)
    Line #498 (got 2 columns instead of 1)

In [ ]:
print(filedata>50)
print(filedata[filedata>50])


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])

In [ ]:
print(np.any(filedata>50,axis=0))
print(np.all(filedata>50,axis=0))
print(np.any(filedata>50,axis=1))
print(np.all(filedata>50,axis=1))

In [ ]:
print((filedata>50) & (filedata<100))
print(~(filedata>50) & (filedata<100))

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [
               16, 17, 18, 19, 20], [21, 22, 23, 24, 25],[26,27,28,29,30]])
print(arr)
print(arr[2:4, 0:2])
print(arr[[0, 1, 2, 3], [1, 2, 3, 4]])
print(arr[[0, 4, 5],3:])
